| **Task Details** | **Information** |
|------------------|-----------------|
| **Task Name** | Task-9 |
| **Student Name** | Ali Husnain Nazar |
| **Roll No** | SU92-BSAIM-F24-024 |
| **University Name** | Superior University |
| **Department** | Bachelor of Science in Artificial Intelligence (BSAI) |
| **Semester** | 3rd Semester |
| **Session** | Fall 2024 |
| **Subject** | (AAI-LAB) |
| **Instructor Name** | (Sir Rasik) |
| **Submission Date** | (05-Nov-2025) |

<div class="alert alert-block alert-success">
    Successfully installed <b>Python 3.10</b>
</div>

<div class="alert alert-block alert-success">
    Import Libraries <b>Pandas, Matplotlib,numpy</b>
</div>

In [8]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

<div class="alert alert-block alert-success">
    Data Loading <b>Credit_card_clean</b>
</div>

In [10]:
df = pd.read_csv('credit_card_clean.csv')

<div class="alert alert-block alert-success">
    top 5  <b>Rows gives from dataset</b>
</div>

In [11]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,798fc410-45c1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,8a8c8f3b-8eb4,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,85698822-43f5,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,0737c11b-be42,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,3b7f77cc-dbc0,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

<div class="alert alert-block alert-success">
    last 5  <b>Rows gives from dataset</b>
</div>

In [12]:
df.tail()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
29995,ecff42d0-bdc6,220000,1,3,1,39,0,0,0,0,...,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29996,99d1fa0e-222b,150000,1,3,2,43,-1,-1,-1,-1,...,8979,5190,0,1837,3526,8998,129,0,0,0
29997,95cdd3e7-4f24,30000,1,2,2,37,4,3,2,-1,...,20878,20582,19357,0,0,22000,4200,2000,3100,1
29998,00d03f02-04cd,80000,1,3,1,41,1,-1,0,0,...,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
29999,15d69f9f-5ad3,50000,1,2,1,46,0,0,0,0,...,36535,32428,15313,2078,1800,1430,1000,1000,1000,1



<div class="alert alert-block alert-success">
     Finding no.Columns  <b>Finding no.Rows </b>
</div>

In [13]:
print ("Rows in data set",df.shape[0])
print ("Columns in data set",df.shape[1])

Rows in data set 30000
Columns in data set 25

In [15]:
print ("Null Values included",df.isnull().sum())

Null Values included ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_1                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [20]:
print ("Type pf each columns",df.dtypes)

Type pf each columns ID                            object
LIMIT_BAL                      int64
SEX                            int64
EDUCATION                      int64
MARRIAGE                       int64
AGE                            int64
PAY_1                         object
PAY_2                          int64
PAY_3                          int64
PAY_4                          int64
PAY_5                          int64
PAY_6                          int64
BILL_AMT1                      int64
BILL_AMT2                      int64
BILL_AMT3                      int64
BILL_AMT4                      int64
BILL_AMT5                      int64
BILL_AMT6                      int64
PAY_AMT1                       int64
PAY_AMT2                       int64
PAY_AMT3                       int64
PAY_AMT4                       int64
PAY_AMT5                       int64
PAY_AMT6                       int64
default payment next month     int64
dtype: object